/**
 * Enable API proposals to try them out. Only valid during development.
 * Extensions cannot be published with this property. For more details visit:
 * https://code.visualstudio.com/api/advanced-topics/using-proposed-api
 *
 * note: This is not a `package.json` official field.
 */
export type EnabledApiProposals = Array<
| 'authSession'
| 'codiconDecoration'
| 'commentsDraftState'
| 'contribCommentEditorActionsMenu'
| 'contribCommentPeekContext'
| 'contribCommentThreadAdditionalMenu'
| 'contribEditorContentMenu'
| 'contribEditSessions'
| 'contribLabelFormatterWorkspaceTooltip'
| 'contribMenuBarHome'
| 'contribMergeEditorMenus'
| 'contribNotebookStaticPreloads'
| 'contribRemoteHelp'
| 'contribShareMenu'
| 'contribViewsRemote'
| 'contribViewsWelcome'
| 'customEditorMove'
| 'debugFocus'
| 'diffCommand'
| 'diffContentOptions'
| 'documentFiltersExclusive'
| 'documentPaste'
| 'dropMetadata'
| 'editorInsets'
| 'editSessionIdentityProvider'
| 'envCollectionWorkspace'
| 'envShellEvent'
| 'extensionRuntime'
| 'extensionsAny'
| 'externalUriOpener'
| 'fileComments'
| 'fileSearchProvider'
| 'findTextInFiles'
| 'formatMultipleRanges'
| 'fsChunks'
| 'getSessions'
| 'handleIssueUri'
| 'idToken'
| 'indentSize'
| 'inlineCompletionsAdditions'
| 'interactive'
| 'interactiveWindow'
| 'ipc'
| 'notebookCellExecutionState'
| 'notebookControllerAffinityHidden'
| 'notebookDeprecated'
| 'notebookExecution'
| 'notebookKernelSource'
| 'notebookLiveShare'
| 'notebookMessaging'
| 'notebookMime'
| 'portsAttributes'
| 'profileContentHandlers'
| 'quickDiffProvider'
| 'quickPickItemTooltip'
| 'quickPickSortByLabel'
| 'resolvers'
| 'saveEditor'
| 'scmActionButton'
| 'scmSelectedProvider'
| 'scmTextDocument'
| 'scmValidation'
| 'semanticSimilarity'
| 'showLocal'
| 'tabInputTextMerge'
| 'taskPresentationGroup'
| 'telemetry'
| 'terminalDataWriteEvent'
| 'terminalDimensions'
| 'terminalQuickFixProvider'
| 'testCoverage'
| 'testObserver'
| 'textSearchProvider'
| 'timeline'
| 'tokenInformation'
| 'treeItemCheckbox'
| 'treeViewReveal'
| 'tunnels'
| 'workspaceTrust'
>
